 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/affiliations", type: :request do
  
  # Affiliation. As you add validations to Affiliation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Affiliation.create! valid_attributes
      get affiliations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      affiliation = Affiliation.create! valid_attributes
      get affiliation_url(affiliation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_affiliation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      affiliation = Affiliation.create! valid_attributes
      get edit_affiliation_url(affiliation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Affiliation" do
        expect {
          post affiliations_url, params: { affiliation: valid_attributes }
        }.to change(Affiliation, :count).by(1)
      end

      it "redirects to the created affiliation" do
        post affiliations_url, params: { affiliation: valid_attributes }
        expect(response).to redirect_to(affiliation_url(Affiliation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Affiliation" do
        expect {
          post affiliations_url, params: { affiliation: invalid_attributes }
        }.to change(Affiliation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post affiliations_url, params: { affiliation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested affiliation" do
        affiliation = Affiliation.create! valid_attributes
        patch affiliation_url(affiliation), params: { affiliation: new_attributes }
        affiliation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the affiliation" do
        affiliation = Affiliation.create! valid_attributes
        patch affiliation_url(affiliation), params: { affiliation: new_attributes }
        affiliation.reload
        expect(response).to redirect_to(affiliation_url(affiliation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        affiliation = Affiliation.create! valid_attributes
        patch affiliation_url(affiliation), params: { affiliation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested affiliation" do
      affiliation = Affiliation.create! valid_attributes
      expect {
        delete affiliation_url(affiliation)
      }.to change(Affiliation, :count).by(-1)
    end

    it "redirects to the affiliations list" do
      affiliation = Affiliation.create! valid_attributes
      delete affiliation_url(affiliation)
      expect(response).to redirect_to(affiliations_url)
    end
  end
end
